### ISSUE TITLE
Unable to create repository using up cli

### ISSUE THREAD

**Issue by jeringk** [upbound/up#280]
### What happened?

Hi Team,
I am trying to create a repository by following instruction mentioned [here](https://docs.upbound.io/upbound-marketplace/packages/#push-a-package).
However I am facing issue while creating repo.
```
> up login
 abcd@mail.com logged in
> up repository create ocicloud
up: error: unknown error:
> up -v
v0.15.0
```

At this point I don't have any other logs.

This happened in my mac.

**Comment by hasheddan** [comment]
@jeringk thanks for the report and apologies for how opaque this error is! What do you see when you run `up repo list`?

**Comment by jeringk** [comment]
```
up repo list
up: error: resource not found: 404 page not found
```

**Comment by jeringk** [comment]
Tried with version `0.14.0`
`up repo list` is showing same error even after logout
```
➜ ./up -v
v0.14.0
➜ ./up logout
<email> logged out
➜  ./up repo list
up: error: resource not found: 404 page not found
```

**Comment by hasheddan** [comment]
@jeringk I am guessing there is some configuration value pointing you to the wrong location. Could you provide the output for:

`up profile view`

`env | grep UP_`

**Comment by jeringk** [comment]
```
./up profile view
{
    "default": {
        "id": "<email>",
        "type": "user",
        "session": "REDACTED"
    }
}
env | grep UP_  returned empty
```

**Comment by jeringk** [comment]
```
➜  upcli ./up login
Username: email.com
Password:
email.com logged in
➜  upcli ./up profile view
{
    "default": {
        "id": "email.com",
        "type": "user",
        "session": "REDACTED"
    }
}
➜  upcli env | grep UP_
```

**Comment by jeringk** [comment]
fyi
For login to `upbound`, I am using `sign in with your email` and not `google` or `github` sso.

**Comment by hasheddan** [comment]
Identified issue here: if user logs in with email then we don't know what account to use as default (i.e. we try to use the email address). We should handle this more gracefully 👍🏻

**Comment by cychiang** [comment]
Hi @hasheddan I want to report a similar issue when using `token` to authenticate in `up` cli. The `account` is missing when doing: `up profile view` and shows as following: 
```
{
    "default": {
        "id": "XXX",
        "type": "token",
        "session": "REDACTED"
    }
}
```
But managed to solve it by putting the `account` into `$UP_ACCOUNT` environment viable. 

When there is no `account`, basically all subcommand like `create`, `list` and `delete` under `repository` will give you: 
```
up: error: resource not found: 404 page not found
```

However, it will work when using `delete` and `create` in a format that contains correct account: `$UP_ACCOUNT/$REPOSITORY_NAME` 

I think it's because the implementation takes `account` and `name` as input variables to form the correct url: 
- https://github.com/upbound/up/blob/main/cmd/up/repository/delete.go#L65
- https://github.com/upbound/up/blob/main/cmd/up/repository/create.go#L34
