### ISSUE TITLE
`up cfg` has no usefulness in Spaces-based Upbound

### ISSUE THREAD

**Issue by cwilhit** [upbound/up#493]
### What happened?

`up cfg` is a set of commands to interact with Upbound Deployment Service and git-managed configurations. This feature doesn't exist in Cloud Spaces/Connected Spaces and there's no plan of record for making the feature available there currently. In the latest releases of `up`, because we're breaking with backwards compat for legacy Spaces, I suggest we leave the command stub there and print an error message explaining that it's not supported in Cloud/Connected Spaces.

**Comment by jastang** [comment]
should we do this in one release without warning? I'd advocate for a documented deprecation notice/period of one release and give any potential users out there that may use it for CI/automation to adjust before removing it altogether

**Comment by adamwg** [comment]
@RedbackThomson mentioned that the latest version of the CLI doesn't work with legacy managed control planes, which is the only place where configurations are applicable. If that's true, any reason to stub the command out rather than removing it outright? Presumably any users with legacy control planes will be pinned to an older CLI version.
