### ISSUE TITLE
Better Compatibility on KUBECONFIG with other Kubernetes Clients

### ISSUE THREAD

**Issue by ulucinar** [upbound/up#77]
Currently, if `KUBECONFIG` env. variable points to a list of kubeconfig files delimited by `:`, `up` fails with the following error:
```
Usage: up cloud login

Login to Upbound Cloud.

Flags:
  -h, --help                               Show context-sensitive help.
  -v, --version                            Print version and exit.

      --endpoint=https://api.upbound.io    Endpoint used for Upbound API ($UP_ENDPOINT).
      --profile=STRING                     Profile used to execute command ($UP_PROFILE).
  -a, --account=STRING                     Account used to execute command ($UP_ACCOUNT).

  -u, --username=STRING                    Username used to execute command ($UP_USER).
  -p, --password=STRING                    Password for specified user. '-' to read from stdin ($UP_PASSWORD).
  -t, --token=STRING                       Token used to execute command. '-' to read from stdin ($UP_TOKEN).

up: error: --kubeconfig: stat file1:file2: no such file or directory (from envar KUBECONFIG="file1:file2")
```

Under the same environment, `kubectl` works as expected. I have tested this with `up cloud login` as shown above.

**Comment by hasheddan** [comment]
Thanks for opening this @ulucinar! This is currently failing because we have the `existingfile` distinction on the flag / env var. I think there are two bugs here:
1. I would prefer if kong (the CLI framework) did not attempt to resolve flags / env vars that were not on the invoked command path (i.e. I don't want it to validate `KUBECONFIG` when it is not relevant for `up cloud login`). I'll work to fix this upstream :)
2. We should honor the upstream supported `KUBECONFIG` format as you suggest. I'll remove `existingfile` distinction and implement custom parsing on this value or consume a k8s upstream implementation
